### PR TITLE
Deserialize translated field

### PR DESCRIPTION
**Pull request by jrief**
In some of my projects I use ``TranslatedField`` with a related model holding the translations.
Unfortunately the serializer for this kind of field is read-only and can't be used for deserialization. 
This pull request adds write support for that field.

In addition I split ``TranslatableModelSerializer`` into ``TranslatableModelSerializerMixin`` which can be applied to existing serializers.

There is also a bug fix, where the code checked for ``TranslatableModel`` rather than ``TranslatableModelMixin``.

### CODE REVIEW

**Comment by jrief** [comment]
@vdboor Codacity complains about method `TranslatedField.to_internal_value(...)`, which according to its standards, should be a function instead.
This in my opinion is a false claim, because that method is overridden from its base class. How can I solve this?

**Comment by jrief** [comment]
@vdboor any comments on this pull request? It's so silent here.

**Comment by jrief** [comment]
@vdboor ping

**Comment by vdboor** [comment]
Looks good to me! The only thing on my mind is, how would this field deal with languages are aren't mentioned in the REST call?

Commit-wise I would have preferred a single commit that refactors the mixin-logic, and another adding the `TranslatedField` logic. This would be hard to change now I think

**Comment by jrief** [comment]
> The only thing on my mind is, how would this field deal with languages are aren't mentioned in the REST call?

The deserialization creates a `TranslatedPicture` object for each language. I've just added a test to check, if fallback then still works.

**Comment by jrief** [comment]
@vdboor I'm going to merge this and release it as version 2.1
I need to deserialize translated fields, and this feature was missing until now.

**Pull request merged**
